development:
    adapter: mysql
    host: localhost
    database: favourite_tweets
    username: root
    password: password
    pool: 5
    timeout: 5000

test:
    adapter: mysql
    host: localhost
    database: test_favourite_tweets
    username: root
    password: password
    pool: 5
    timeout: 5000

production:
    adapter: mysql
    host: localhost
    database: favourite_tweets
    username: root
    password: password
    pool: 5
    timeout: 5000